spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_blog_db?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    #this part is different from initial project
    druid:
      initial-size: 20
      min-idle: 10
      test-while-idle: true
      validation-query: select 1
      max-active: 100



